::: {.tikz-desc data-node="sdata"}
**Private data**: Sender's sensitive data, held privately and never shared.

$$x \in \mathsf{X}$$
:::

::: {.tikz-desc data-node="mech"}
**Mechanism**: A (deterministic or randomised) mechanism.

$$M: (\mathsf{X}, \mathcal{T}) \rightarrow [0,1]$$

Markov kernel w.r.t. measurable space $(\mathsf{T}, \mathcal{T})$.

:::

::: {.tikz-desc data-node="sstat"}
**Statistic**: Generated from mechanism and shared with Receiver.

$$T \sim M(x, \cdot)$$
:::

::: {.tikz-desc data-node="strans"}
**Privacy guarantee**: Shared with Receiver for transparency.

<br>

:::{.callout-note}
## Assumption 1

Sender shares the mechanism $M$ and privacy class $\mathfrak{C}$ with Receiver. Further, the definitions of $M$ and $\mathfrak{C}$ do not depend on the data.

:::

:::

::: {.tikz-desc data-node="spriv"}
**Privacy function**: The realised privacy is

$$
\rho(d^{Q_T},x)
$$

<br> <br>

::: {.callout-note}
## Proper scoring representation

Define $S: \mathcal{P} \times \mathsf{X} \rightarrow \mathbb{R}$ as

$$
S(P,x) = \rho(d^{P},x),
$$
if $\ell = \rho$ and then $S$ is a (negatively-orientated) proper scoring rule.

:::

:::


::: {.tikz-desc data-node="adata"}
**Data-prior** $Q$ the receiver's assumed prior over the data.

$$Q \in \mathcal{P}(\mathsf{X})$$
:::

::: {.tikz-desc data-node="apost"}
**Data-posterior.** Receiver's posterior given the release of $T$.

$$Q_T = Q(\,\cdot \mid T)$$

:::

::: {.tikz-desc data-node="aact"}
**Receiver decision**: $d$, formed by posterior $Q_T$ and loss $\ell$.

$$
d^{Q_T} \in \arg\inf_{d \in \mathcal{D}} \mathbb{E}_{z \sim Q_T}[ \ell(d,z)]
$$

:::

::: {.tikz-desc data-node="aloss"}
**Receiver loss**: Receiver's loss function for decision making. 

<br>

::: {.callout-note}
## Assumption 3

Receiver's targets the privacy function of Sender, that is $\ell = \rho$.

:::

:::

::: {.tikz-desc data-node="statbox"}
**Sender**: Holds $x$ and chooses $M$ to persuade Receiver.

<br> <br> <br> <br>

::: {.callout-note}
## Assumption 4

For a given $Q$ and $x$, Sender considers a mechanism $M$ private only if

$$\mathbb{P}_x\left[S(Q,x) - S(Q_T,x) \leq \kappa \right] \geq 1 - \delta.$${#eq-tailproob}
:::

::: {.callout-note}
## Assumption 5

Let $\mathcal{Q}_x \subset \mathcal{P}(\mathsf{X})$ be some class of prior distributions over the dataset. 

Sender considers $M$ private if [-@eq-tailproob] holds uniformly for all data-priors $Q \in \mathcal{Q}_x$ and datasets $x \in \mathsf{X}$.

:::

:::

::: {.tikz-desc data-node="advbox"}
**Receiver**: Holds prior $Q$ over (unknown) data $x$.

<br>


::: {.callout-note}
## Assumption 2

Receiver is Bayes rational.
:::

:::
